"""add_message_deletion_support

Revision ID: 1b389d624711
Revises: 0e8bf552ae18
Create Date: 2026-06-02 06:09:29.749044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b389d624711'
down_revision: Union[str, None] = '0e8bf552ae18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_deleted_for_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_uid', sa.String(), nullable=True),
    sa.Column('user_uid', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_uid'], ['messages.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_deleted_for_users_id'), 'message_deleted_for_users', ['id'], unique=False)
    op.create_index(op.f('ix_message_deleted_for_users_message_uid'), 'message_deleted_for_users', ['message_uid'], unique=False)
    op.create_index(op.f('ix_message_deleted_for_users_user_uid'), 'message_deleted_for_users', ['user_uid'], unique=False)
    op.add_column('messages', sa.Column('deleted_by_uid', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('deleted_by_user_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('deleted_by_user_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('deleted_for_json', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['deleted_by_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'deleted_for_json')
    op.drop_column('messages', 'deleted_by_user_at')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'deleted_by_user_type')
    op.drop_column('messages', 'deleted_by_uid')
    op.drop_index(op.f('ix_message_deleted_for_users_user_uid'), table_name='message_deleted_for_users')
    op.drop_index(op.f('ix_message_deleted_for_users_message_uid'), table_name='message_deleted_for_users')
    op.drop_index(op.f('ix_message_deleted_for_users_id'), table_name='message_deleted_for_users')
    op.drop_table('message_deleted_for_users')
    # ### end Alembic commands ###
