"""add_attendance_address_fields

Revision ID: 2c7253e8acff
Revises: e33710b430cf
Create Date: 2026-04-28 17:41:54.689835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c7253e8acff'
down_revision: Union[str, None] = 'e33710b430cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('user_uid', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('company_uid', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('start_latitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('start_longitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('end_latitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('end_longitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('work_hours', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('start_address', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('end_address', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_attendance_company_uid'), 'attendance', ['company_uid'], unique=False)
    op.create_index(op.f('ix_attendance_user_uid'), 'attendance', ['user_uid'], unique=False)
    op.drop_column('attendance', 'type')
    op.drop_column('attendance', 'marked_at')
    op.drop_column('attendance', 'latitude')
    op.drop_column('attendance', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('marked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_attendance_user_uid'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_company_uid'), table_name='attendance')
    op.drop_column('attendance', 'status')
    op.drop_column('attendance', 'end_address')
    op.drop_column('attendance', 'start_address')
    op.drop_column('attendance', 'work_hours')
    op.drop_column('attendance', 'end_longitude')
    op.drop_column('attendance', 'end_latitude')
    op.drop_column('attendance', 'start_longitude')
    op.drop_column('attendance', 'start_latitude')
    op.drop_column('attendance', 'end_at')
    op.drop_column('attendance', 'start_at')
    op.drop_column('attendance', 'company_uid')
    op.drop_column('attendance', 'user_uid')
    # ### end Alembic commands ###
