"""deleted_by_member_fk

Revision ID: 2fb329a5ddca
Revises: 66f86c10d7dc
Create Date: 2026-05-15 16:18:04.635038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb329a5ddca'
down_revision: Union[str, None] = '66f86c10d7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notifications', 'members', ['deleted_by'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    # ### end Alembic commands ###
