"""remove_deleted_for_json_redundant_column

Revision ID: 44e8289d42dc
Revises: 1b389d624711
Create Date: 2026-06-02 06:17:20.315046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e8289d42dc'
down_revision: Union[str, None] = '1b389d624711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deleted_for_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('deleted_for_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###
