"""add_fcm_token_and_update_notifications

Revision ID: 4a505f3f192a
Revises: fc2d4842e3b6
Create Date: 2026-05-13 11:05:03.997501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4a505f3f192a'
down_revision: Union[str, None] = 'fc2d4842e3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.String(), nullable=True),
    sa.Column('profile_uid', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=False),
    sa.Column('user_role', postgresql.ENUM('owner', 'worker', name='userrole', create_type=False), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uid', 'device_id', name='_user_device_fcm_uc')
    )
    op.create_index(op.f('ix_fcm_tokens_device_id'), 'fcm_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_fcm_tokens_id'), 'fcm_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_fcm_tokens_user_uid'), 'fcm_tokens', ['user_uid'], unique=False)
    op.add_column('notifications', sa.Column('profile_uid', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('data_payload', sa.Text(), nullable=True))
    notification_status = postgresql.ENUM('sent', 'delivered', 'read', name='notificationstatus')
    notification_status.create(op.get_bind())
    op.add_column('notifications', sa.Column('status', notification_status, nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('seen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'seen_at')
    op.drop_column('notifications', 'delivered_at')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'data_payload')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'profile_uid')
    op.drop_index(op.f('ix_fcm_tokens_user_uid'), table_name='fcm_tokens')
    op.drop_index(op.f('ix_fcm_tokens_id'), table_name='fcm_tokens')
    op.drop_index(op.f('ix_fcm_tokens_device_id'), table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    # ### end Alembic commands ###
