"""make_more_job_fields_non_nullable

Revision ID: 51d9dd4f3860
Revises: 891871bbda13
Create Date: 2026-05-13 06:00:35.255353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d9dd4f3860'
down_revision: Union[str, None] = '891871bbda13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'worker_account_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'require_photo_on_start',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'require_photo_on_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'capture_location',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'capture_location',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'require_photo_on_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'require_photo_on_start',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'worker_account_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
