"""Add job chat tables

Revision ID: 60f15a50f18e
Revises: 051d1788456a
Create Date: 2026-05-18 11:53:21.850390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f15a50f18e'
down_revision: Union[str, None] = '051d1788456a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_chat_messages',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('created_by_uid', sa.String(), nullable=True),
    sa.Column('created_by_profile_uid', sa.String(), nullable=True),
    sa.Column('author_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_author_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_profile_uid'], ['members.uid'], ),
    sa.ForeignKeyConstraint(['created_by_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_job_chat_messages_job_id'), 'job_chat_messages', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_chat_messages_uid'), 'job_chat_messages', ['uid'], unique=False)
    op.create_table('job_chat_message_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_uid', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_uid'], ['job_chat_messages.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_chat_message_contents_id'), 'job_chat_message_contents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_chat_message_contents_id'), table_name='job_chat_message_contents')
    op.drop_table('job_chat_message_contents')
    op.drop_index(op.f('ix_job_chat_messages_uid'), table_name='job_chat_messages')
    op.drop_index(op.f('ix_job_chat_messages_job_id'), table_name='job_chat_messages')
    op.drop_table('job_chat_messages')
    # ### end Alembic commands ###
