"""add_deleted_at_and_by

Revision ID: 66f86c10d7dc
Revises: a1422a5ed06d
Create Date: 2026-05-15 16:16:44.934889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f86c10d7dc'
down_revision: Union[str, None] = 'a1422a5ed06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('deleted_by', sa.String(), nullable=True))
    op.alter_column('notifications', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('notifications', 'deleted_by')
    op.drop_column('notifications', 'deleted_at')
    # ### end Alembic commands ###
