"""add_created_by_profile_uid_to_job

Revision ID: 7a6014fc81dc
Revises: c1653020a43c
Create Date: 2026-05-18 12:38:22.587563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6014fc81dc'
down_revision: Union[str, None] = 'c1653020a43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_by_profile_uid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'members', ['created_by_profile_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'created_by_profile_uid')
    # ### end Alembic commands ###
