"""restore metadata_json to chat contents

Revision ID: 89006e95d960
Revises: fb04c27958a4
Create Date: 2026-05-21 13:37:10.774829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89006e95d960'
down_revision: Union[str, None] = 'fb04c27958a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_chat_message_contents', sa.Column('metadata_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_chat_message_contents', 'metadata_json')
    # ### end Alembic commands ###
