"""make_job_fields_non_nullable

Revision ID: 891871bbda13
Revises: 6645a1b105ef
Create Date: 2026-05-13 05:59:33.476723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891871bbda13'
down_revision: Union[str, None] = '6645a1b105ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
