"""Add JobActivity table

Revision ID: 93658ab91986
Revises: aa9c53068318
Create Date: 2026-05-21 09:59:28.435105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93658ab91986'
down_revision: Union[str, None] = 'aa9c53068318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('profile_uid', sa.String(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['profile_uid'], ['members.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_activities_id'), 'job_activities', ['id'], unique=False)
    op.create_index(op.f('ix_job_activities_job_id'), 'job_activities', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_activities_profile_uid'), 'job_activities', ['profile_uid'], unique=False)
    op.create_index(op.f('ix_job_activities_uid'), 'job_activities', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_activities_uid'), table_name='job_activities')
    op.drop_index(op.f('ix_job_activities_profile_uid'), table_name='job_activities')
    op.drop_index(op.f('ix_job_activities_job_id'), table_name='job_activities')
    op.drop_index(op.f('ix_job_activities_id'), table_name='job_activities')
    op.drop_table('job_activities')
    # ### end Alembic commands ###
