"""make_notification_fields_not_null

Revision ID: 95142f3caede
Revises: 4a505f3f192a
Create Date: 2026-05-13 11:07:29.087599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95142f3caede'
down_revision: Union[str, None] = '4a505f3f192a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fcm_tokens', 'user_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fcm_tokens', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fcm_tokens', 'user_role',
               existing_type=postgresql.ENUM('owner', 'worker', name='userrole'),
               nullable=False)
    op.alter_column('fcm_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'user_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('sent', 'delivered', 'read', name='notificationstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('sent', 'delivered', 'read', name='notificationstatus'),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'user_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fcm_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('fcm_tokens', 'user_role',
               existing_type=postgresql.ENUM('owner', 'worker', name='userrole'),
               nullable=True)
    op.alter_column('fcm_tokens', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fcm_tokens', 'user_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
