"""sync_notifications

Revision ID: a1422a5ed06d
Revises: 8b642d2f8753
Create Date: 2026-05-15 16:15:02.964393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1422a5ed06d'
down_revision: Union[str, None] = '8b642d2f8753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'message', new_column_name='body', existing_type=sa.Text())
    op.alter_column('notifications', 'is_seen', new_column_name='seen', existing_type=sa.Boolean())
    op.alter_column('notifications', 'is_deleted', new_column_name='deleted', existing_type=sa.Boolean())
    op.alter_column('notifications', 'profile_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_notifications_profile_uid'), 'notifications', ['profile_uid'], unique=False)
    op.create_foreign_key(None, 'notifications', 'members', ['profile_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_profile_uid'), table_name='notifications')
    op.alter_column('notifications', 'profile_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'body', new_column_name='message', existing_type=sa.VARCHAR())
    op.alter_column('notifications', 'seen', new_column_name='is_seen', existing_type=sa.BOOLEAN())
    op.alter_column('notifications', 'deleted', new_column_name='is_deleted', existing_type=sa.BOOLEAN())
    # ### end Alembic commands ###
