"""Add worker_activity to jobs

Revision ID: aa9c53068318
Revises: 7a6014fc81dc
Create Date: 2026-05-21 09:54:06.297644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9c53068318'
down_revision: Union[str, None] = '7a6014fc81dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('worker_activity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'worker_activity')
    # ### end Alembic commands ###
