"""add_job_lifecycle_timestamps

Revision ID: beedaa4306b8
Revises: 81db1f879808
Create Date: 2026-05-10 08:03:17.439867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beedaa4306b8'
down_revision: Union[str, None] = '81db1f879808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'updated_at')
    # ### end Alembic commands ###
