"""Rename message to chat_message

Revision ID: c1653020a43c
Revises: 60f15a50f18e
Create Date: 2026-05-18 12:04:57.554218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1653020a43c'
down_revision: Union[str, None] = '60f15a50f18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_chat_message_contents', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_chat_message_contents', 'message')
    # ### end Alembic commands ###
