"""remove_description_from_jobs

Revision ID: c245e016a043
Revises: d4e5f6g7h8i9
Create Date: 2026-05-07 18:05:07.901800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c245e016a043'
down_revision: Union[str, None] = 'd4e5f6g7h8i9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_account_uid'), table_name='attendance')
    op.add_column('jobs', sa.Column('company_uid', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('created_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_company_uid'), 'jobs', ['company_uid'], unique=False)
    op.create_foreign_key(None, 'jobs', 'companies', ['company_uid'], ['company_id'])
    op.create_foreign_key(None, 'jobs', 'users', ['created_by'], ['uid'])
    op.drop_column('jobs', 'description')
    op.drop_constraint(op.f('uq_members_account_uid'), 'members', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_members_account_uid'), 'members', ['account_uid'], postgresql_nulls_not_distinct=False)
    op.add_column('jobs', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_company_uid'), table_name='jobs')
    op.drop_column('jobs', 'created_by')
    op.drop_column('jobs', 'company_uid')
    op.create_index(op.f('ix_attendance_account_uid'), 'attendance', ['account_uid'], unique=False)
    # ### end Alembic commands ###
