"""add is_deleted to notifications

Revision ID: c37e7c7baa04
Revises: 8e2cfe2b98b1
Create Date: 2026-05-15 11:30:02.286427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37e7c7baa04'
down_revision: Union[str, None] = '8e2cfe2b98b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_deleted')
    # ### end Alembic commands ###
