"""Simplify activity architecture

Revision ID: fb04c27958a4
Revises: 93658ab91986
Create Date: 2026-05-21 10:40:59.301497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb04c27958a4'
down_revision: Union[str, None] = '93658ab91986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_activities', sa.Column('actor_type', sa.String(), nullable=False))
    op.drop_column('job_chat_message_contents', 'metadata_json')
    op.drop_column('jobs', 'worker_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('worker_activity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_chat_message_contents', sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('job_activities', 'actor_type')
    # ### end Alembic commands ###
