"""make_member_fields_non_nullable

Revision ID: fc2d4842e3b6
Revises: 51d9dd4f3860
Create Date: 2026-05-13 06:02:21.904922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc2d4842e3b6'
down_revision: Union[str, None] = '51d9dd4f3860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'user_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('members', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'user_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
